# Generated by Django 4.2.19 on 2025-02-21 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_todo_due_date_todo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('Not-Started', 'Not Started'), ('InProgress', 'In Progress'), ('Completed', 'Completed')], default='not_started', max_length=20),
        ),
    ]
