# Generated by Django 4.2.19 on 2025-02-23 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_todo_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
