# Generated by Django 4.2.19 on 2025-02-24 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='mark_as_important',
            field=models.BooleanField(default=False),
        ),
    ]
