# Generated by Django 4.2.19 on 2025-02-25 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_todo_mark_as_important'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
